name: Publish Extension

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install VSCE
        run: npm install -g @vscode/vsce
      
      - name: Publish Extension
        run: vsce publish -p ${{ secrets.VS_MARKETPLACE_TOKEN }}
